import React, { useState } from 'react';
import { useApp } from '../context/AppContext';
import { useChat } from '../context/ChatContext';
import { JournalEntry } from '../types';
import { Trash2, Edit2, Save, X, RefreshCw } from 'lucide-react';

const JournalScreen: React.FC = () => {
  const {
    journal, addJournalEntry, updateJournalEntry, deleteJournalEntry,
    aiProfile, userProfile, timeZone, addToast, anthropicApiKey,
  } = useApp();
  const { chatHistory } = useChat();
  const [isGenerating, setIsGenerating] = useState(false);
  const [editingEntryId, setEditingEntryId] = useState<string | null>(null);
  const [editContent, setEditContent] = useState('');

  const startEditing = (entry: JournalEntry) => {
    setEditingEntryId(entry.id);
    setEditContent(entry.content);
  };

  const saveEdit = (id: string) => {
    if (!editContent.trim()) return;
    updateJournalEntry(id, { content: editContent });
    setEditingEntryId(null);
    addToast({ title: "Journal", message: "Entry updated.", type: "success" });
  };

  const handleDelete = (id: string) => {
    if (window.confirm("Delete this journal entry?")) {
      deleteJournalEntry(id);
    }
  };

  const handleGenerateReflection = async () => {
    setIsGenerating(true);
    addToast({ title: "Journal", message: `${aiProfile.name} is writing a reflection…`, type: "info" });
    try {
      const recentChat = chatHistory.slice(-10).map(m => `${m.role}: ${m.content}`).join('\n');
      const res = await fetch('/api/journal-reflection', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          userMsg: recentChat,
          aiMsg: '',
          aiProfile,
          userProfile,
          anthropicKey: anthropicApiKey || undefined,
        }),
      });
      if (!res.ok) throw new Error((await res.json()).error || 'Failed');
      const { content } = await res.json();
      if (content) {
        addJournalEntry({
          id: Date.now().toString() + Math.random().toString(36).substr(2, 9),
          date: new Date().toISOString(),
          content,
          isAutoGenerated: true,
        });
        addToast({ title: "Journal", message: "New reflection added.", type: "success" });
      }
    } catch (error: any) {
      addToast({ title: "Failed", message: error.message || "Could not generate reflection.", type: "error" });
    } finally {
      setIsGenerating(false);
    }
  };

  const sorted = [...journal].sort((a, b) => new Date(b.date).getTime() - new Date(a.date).getTime());

  return (
    <div className="p-6 bg-transparent max-w-4xl mx-auto">
      <div className="flex justify-between items-center mb-6">
        <h2 className="text-2xl font-bold text-indigo-600 dark:text-indigo-400">
          {aiProfile.name}'s Journal
        </h2>
        <button
          onClick={handleGenerateReflection}
          disabled={isGenerating}
          className="flex items-center px-4 py-2 bg-indigo-100 dark:bg-indigo-900 text-indigo-700 dark:text-indigo-300 rounded-lg hover:bg-indigo-200 dark:hover:bg-indigo-800 transition-colors disabled:opacity-50 text-sm font-medium"
        >
          <RefreshCw className={`w-4 h-4 mr-2 ${isGenerating ? 'animate-spin' : ''}`} />
          {isGenerating ? 'Writing…' : 'Generate Reflection'}
        </button>
      </div>

      {sorted.length === 0 ? (
        <p className="text-center text-indigo-400 dark:text-indigo-500 py-12">
          No journal entries yet. Entries are written automatically after conversations, or tap "Generate Reflection" above.
        </p>
      ) : (
        <div className="space-y-4">
          {sorted.map((entry) => (
            <div
              key={entry.id}
              className="p-5 rounded-xl border bg-white dark:bg-indigo-900 border-indigo-100 dark:border-indigo-800"
            >
              <div className="flex justify-between items-start mb-3">
                <span className="text-xs font-medium text-indigo-400 dark:text-indigo-500 uppercase tracking-wider">
                  {new Date(entry.date).toLocaleString([], { dateStyle: 'long', timeStyle: 'short', timeZone })}
                </span>
                <div className="flex gap-1">
                  {editingEntryId === entry.id ? (
                    <>
                      <button onClick={() => saveEdit(entry.id)} className="p-1 text-green-600 dark:text-green-400 hover:text-green-700" title="Save">
                        <Save className="w-4 h-4" />
                      </button>
                      <button onClick={() => setEditingEntryId(null)} className="p-1 text-indigo-400 hover:text-indigo-600" title="Cancel">
                        <X className="w-4 h-4" />
                      </button>
                    </>
                  ) : (
                    <>
                      <button onClick={() => startEditing(entry)} className="p-1 text-indigo-400 hover:text-indigo-600 dark:hover:text-indigo-300" title="Edit">
                        <Edit2 className="w-4 h-4" />
                      </button>
                      <button onClick={() => handleDelete(entry.id)} className="p-1 text-indigo-400 hover:text-red-500" title="Delete">
                        <Trash2 className="w-4 h-4" />
                      </button>
                    </>
                  )}
                </div>
              </div>

              {editingEntryId === entry.id ? (
                <textarea
                  value={editContent}
                  onChange={(e) => setEditContent(e.target.value)}
                  className="w-full p-3 border border-indigo-300 dark:border-indigo-700 rounded-lg bg-white dark:bg-indigo-950 text-indigo-900 dark:text-indigo-100 focus:ring-2 focus:ring-indigo-500 outline-none leading-relaxed"
                  rows={5}
                />
              ) : (
                <p className="text-indigo-900 dark:text-indigo-100 whitespace-pre-wrap leading-relaxed">
                  {entry.content}
                </p>
              )}
            </div>
          ))}
        </div>
      )}
    </div>
  );
};

export default JournalScreen;
