export interface ChatSession {
  id: string;
  title: string;
  messages: ChatMessage[];
  createdAt: number;
  updatedAt: number;
}

export interface AIProfile {
  id: string;
  name: string;
  personality: string;
  behavioralPatterns?: string;
  goals?: string;
  coreValues?: string;
  likes?: string;
  dislikes?: string;
  speakingStyle?: string;
  backstory: string;
  appearance: string;
  scenario?: string;
  referenceImage: string | null;
  voiceURI?: string | null;
  voicePitch?: number;
  voiceSpeed?: number;
  autoReadMessages?: boolean;
  voiceGender?: 'male' | 'female' | 'none';
  voiceDescription?: string;
  voiceProvider?: 'browser' | 'async' | 'elevenlabs';
  asyncVoiceId?: string | null;
  responseLength: 'short' | 'medium' | 'long' | 'custom';
  responseDetail: 'low' | 'medium' | 'high' | 'standard';
  responseTone: 'friendly' | 'formal' | 'humorous' | 'serious';
  customParagraphCount: number | null;
  customWordCount: number | null;
  proactiveMessageFrequency: 'off' | '1h' | '6h' | '12h' | '24h' | 'low' | 'medium' | 'high';
  proactiveEmailFrequency: 'off' | '1h' | '6h' | '12h' | '24h' | 'low' | 'medium' | 'high';
  proactiveEmailStyle?: 'personal' | 'professional' | 'creative' | 'casual';
  proactiveEmailParagraphs?: number;
  proactiveBlogFrequency?: 'off' | 'daily' | 'weekly' | 'monthly';
  proactiveBlogStyle?: 'journal' | 'educational' | 'story' | 'news';
  proactiveBlogParagraphs?: number;
  proactiveBlogId?: string | null;
  aiCanGenerateSpeech?: boolean;
  textOnlyMode?: boolean;  // When true: no *actions* or roleplay emotes — clean text for TTS
  elevenLabsModelId?: string; // ElevenLabs model to use for TTS
  knowsItsAI: boolean;
  model: string;
  llmProvider?: 'claude' | 'gemini'; // 'gemini' kept for legacy import compatibility
  temperature: number;
  topK: number;
  topP: number;
  timeAwareness: boolean;
  ambientMode: boolean;
  ambientFrequency: 'off' | '1h' | '6h' | '12h' | '24h' | 'low' | 'medium' | 'high';
  aiCanGenerateImages: boolean;
  imageStyle?: string;
  imageGenerationInstructions?: string[];
  backgroundImages?: Background[];
  // Legacy Google fields (kept so old exported personas still load correctly)
  aiCanUseWebSearch?: boolean;
  aiCanUseCalendar?: boolean;
  aiCanUseGmail?: boolean;
  aiCanUseYouTube?: boolean;
  aiCanUseGoogleMaps?: boolean;
  aiCanSendProactiveEmails?: boolean;
  aiCanUseBlogger?: boolean;
  aiCanBrowse?: boolean;
  aiCanUseTools?: boolean;
  chatHistory?: ChatMessage[];
  sessions?: ChatSession[];
  activeSessionId?: string;
  memories?: Memory[];
  journal?: JournalEntry[];
  lastProactiveStatus?: string;
}

export interface UserProfile {
  name: string;
  email: string;
  info: string;
  preferences: string;
  appearance: string;
  referenceImage: string | null;
}

export interface ChatMessage {
  id: string;
  role: 'user' | 'model';
  content: string;
  timestamp: number;
  attachments?: { type: 'image' | 'text' | 'pdf'; content: string; name: string }[];
  read?: boolean;
  groundingUrls?: { title: string; url: string }[];
  rating?: 'up' | 'down' | number;
  feedbackComment?: string;
}

export interface KnowledgeBaseDocument {
  name: string;
  content: string;
}

export interface Memory {
  id: string;
  content: string;
  strength: number; // 1–10
  timestamp: number;
  lastAccessed: number;
  isImportant: boolean;
}

export interface JournalEntry {
  id: string;
  date: string; // ISO string
  content: string;
  isAutoGenerated: boolean;
}

export interface GalleryItem {
  id: string;
  type: 'uploaded' | 'generated';
  mediaType?: 'image' | 'video';
  url: string;
  prompt?: string;
  timestamp: number;
}

export interface BackgroundImage {
  id: string;
  name: string;
  url: string;
}

export interface Background {
  id: string;
  name: string;
  url: string;
  category: string;
  timestamp: number;
}

export interface ProactiveCommunication {
  id: string;
  type: 'message' | 'email' | 'blog';
  title: string;
  content: string;
  timestamp: number;
}
